In [1]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("AB_NYC_2019.csv")

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [11]:
df.price.describe()

count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [43]:
min_threshold = df.price.quantile(0.001)
max_threshold = df.price.quantile(0.9998)

min_threshold, max_threshold

(18.0, 7500.0)

In [44]:
df[(df.price<min_threshold)]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
2860,1620248,Large furnished 2 bedrooms- - 30 days Minimum,2196224,Sally,Manhattan,East Village,40.73051,-73.98140,Entire home/apt,10,30,0,NaN,NaN,4,137
4647,3258197,Large 1br Duplex in Heart of Upper East Side,16477306,Jeff,Manhattan,Upper East Side,40.76866,-73.95553,Entire home/apt,16,2,21,2019-06-30,1.69,1,9
5542,4031809,Prewar classic NYC apartment.,20902552,Miquel,Manhattan,Washington Heights,40.83456,-73.94344,Private room,16,14,0,NaN,NaN,1,0
8169,6301965,Beautiful SoHo Loft,655506,Silvia,Manhattan,SoHo,40.72340,-73.99967,Entire home/apt,16,3,3,2018-01-08,0.16,1,0
8270,6364324,The Oasis.,33106693,Elena,Manhattan,Harlem,40.82159,-73.95013,Private room,16,2,43,2019-07-01,1.66,3,154
20992,16620607,Spacious and Modern 2 Bedroom Apartment,109725962,Erika,Brooklyn,Bushwick,40.68994,-73.91556,Entire home/apt,11,2,113,2019-06-22,3.86,1,261
21281,16927533,Studio with amazing view,3737986,Carolann,Manhattan,Financial District,40.70588,-74.01590,Entire home/apt,12,300,0,NaN,NaN,1,0
21700,17437106,Couch in Harlem Harvey Refugees only,33511962,Morgan,Manhattan,Harlem,40.81302,-73.95349,Shared room,10,1,0,NaN,NaN,1,0
22261,17952277,"Newly renovated, fully furnished room in Brooklyn",62685070,Katie,Brooklyn,Bushwick,40.69974,-73.91935,Private room,10,5,0,NaN,NaN,1,0
22287,17979764,Jen Apt,84497333,Jennifer,Manhattan,SoHo,40.72237,-73.99817,Private room,10,5,2,2017-04-15,0.07,1,0
22313,18007671,Cute 1 bedroom basement apartment,73228035,Maimi,Brooklyn,East Flatbush,40.66200,-73.93775,Private room,15,1,2,2017-04-17,0.07,2,0
22835,18490141,IT'S SIMPLY CONVENIENT!,97001292,Maria,Queens,Jamaica,40.69085,-73.79916,Entire home/apt,10,1,43,2019-06-12,1.68,1,252
23161,18750597,"Huge Brooklyn Brownstone Living, Close to it all.",8993084,Kimberly,Brooklyn,Bedford-Stuyvesant,40.69023,-73.95428,Private room,0,4,1,2018-01-06,0.05,4,28
23256,18835820,"Quiet, Cozy UES Studio Near the Subway",52777892,Amy,Manhattan,Upper East Side,40.76844,-73.95341,Entire home/apt,10,3,10,2018-10-22,0.39,1,0
24100,19415314,"Girls only, cozy room one block from Times Square",47336995,Mario,Manhattan,Hell's Kitchen,40.75812,-73.98935,Shared room,10,1,2,2017-06-24,0.08,1,0
25433,20333471,★Hostel Style Room | Ideal Traveling Buddies★,131697576,Anisha,Bronx,East Morrisania,40.83296,-73.88668,Private room,0,2,55,2019-06-24,2.56,4,127
25634,20523843,"MARTIAL LOFT 3: REDEMPTION (upstairs, 2nd room)",15787004,Martial Loft,Brooklyn,Bushwick,40.69467,-73.92433,Private room,0,2,16,2019-05-18,0.71,5,0
25753,20608117,"Sunny, Quiet Room in Greenpoint",1641537,Lauren,Brooklyn,Greenpoint,40.72462,-73.94072,Private room,0,2,12,2017-10-27,0.53,2,0
25778,20624541,Modern apartment in the heart of Williamsburg,10132166,Aymeric,Brooklyn,Williamsburg,40.70838,-73.94645,Entire home/apt,0,5,3,2018-01-02,0.15,1,73
25794,20639628,Spacious comfortable master bedroom with nice ...,86327101,Adeyemi,Brooklyn,Bedford-Stuyvesant,40.68173,-73.91342,Private room,0,1,93,2019-06-15,4.28,6,176
25795,20639792,Contemporary bedroom in brownstone with nice view,86327101,Adeyemi,Brooklyn,Bedford-Stuyvesant,40.68279,-73.91170,Private room,0,1,95,2019-06-21,4.37,6,232
25796,20639914,Cozy yet spacious private brownstone bedroom,86327101,Adeyemi,Brooklyn,Bedford-Stuyvesant,40.68258,-73.91284,Private room,0,1,95,2019-06-23,4.35,6,222
26259,20933849,the best you can find,13709292,Qiuchi,Manhattan,Murray Hill,40.75091,-73.97597,Entire home/apt,0,3,0,NaN,NaN,1,0
26841,21291569,Coliving in Brooklyn! Modern design / Shared room,101970559,Sergii,Brooklyn,Bushwick,40.69211,-73.90670,Shared room,0,30,2,2019-06-22,0.11,6,333
26866,21304320,Best Coliving space ever! Shared room.,101970559,Sergii,Brooklyn,Bushwick,40.69166,-73.90928,Shared room,0,30,5,2019-05-24,0.26,6,139
27972,21869057,Spacious 2-bedroom Apt in Heart of Greenpoint,11967922,Vishanti & Jeremy,Brooklyn,Greenpoint,40.72421,-73.95364,Entire home/apt,10,1,93,2019-07-01,4.73,1,32
28019,21893604,Private Bedroom in West Village/Chelsea,1144452,Dante,Manhattan,Chelsea,40.74045,-74.00047,Private room,12,3,8,2019-06-07,0.59,1,37
28242,21981703,Beautiful and Charming 2 Bedroom in Brooklyn!,2066240,Marcella,Brooklyn,Crown Heights,40.67405,-73.94419,Entire home/apt,12,3,0,NaN,NaN,1,0
28841,22258432,Awesome designed shared room in beautiful Coli...,146345538,Sergii,Brooklyn,Bushwick,40.69329,-73.91328,Shared room,15,30,3,2018-07-14,0.16,5,344
31066,24114389,"Very Spacious bedroom, steps from CENTRAL PARK.",180661875,Salim,Manhattan,Upper West Side,40.76844,-73.98333,Private room,10,1,2,2018-04-23,0.13,1,0
31407,24412104,Cozy feel at home studio,91034542,Maureen,Manhattan,Kips Bay,40.74408,-73.97803,Private room,10,5,42,2019-06-30,2.87,1,2
32810,25839759,Gigantic Sunny Room in Park Slope-Private Back...,167570251,Rachel,Brooklyn,Sunset Park,40.66242,-73.99464,Entire home/apt,10,1,14,2018-10-28,1.06,1,4
33225,26235873,Voted #1 Airbnb In NYC,197169969,Maria,Queens,Jamaica,40.68939,-73.79886,Entire home/apt,10,2,22,2019-07-06,1.76,1,332
33448,26443106,"trip NYC - your Couch - clean, cheap, close to...",182488531,Kevin4,Queens,Elmhurst,40.73753,-73.87054,Shared room,15,1,19,2019-06-20,1.71,2,271
33505,26496645,Room with a view,110049861,Martin,Brooklyn,Williamsburg,40.70959,-73.95693,Private room,10,1,0,NaN,NaN,1,83
34446,27316669,Bronx Apart,205820814,Luz,Bronx,Highbridge,40.83454,-73.92751,Private room,10,1,0,NaN,NaN,1,180
35005,27752128,sofa Bed And Breakfast,205706382,Peter,Queens,Maspeth,40.72514,-73.89845,Shared room,11,1,0,NaN,NaN,1,245
35386,28071998,Cozy room in a three-bedroom House,47516406,Arthur,Queens,Woodhaven,40.69139,-73.86086,Private room,10,7,4,2018-10-08,0.41,2,180
35601,28270998,"Charming, bright and brand new Bed-Stuy home",647528,Caterina,Brooklyn,Bedford-Stuyvesant,40.69508,-73.95164,Entire home/apt,10,3,5,2019-07-02,0.51,1,0
36997,29414633,private room,221574115,Ahmet,Brooklyn,Bensonhurst,40.61208,-74.00181,Shared room,15,10,0,NaN,NaN,2,0
38609,30353302,Room close to La Guardia Airport,227905146,Gladys,Queens,East Elmhurst,40.76185,-73.87392,Shared room,16,1,10,2019-06-16,1.36,1,0
45178,34577268,The duplex of city center,257474717,Kim,Queens,Flushing,40.75498,-73.83423,Entire home/apt,15,2,0,NaN,NaN,1,361
45646,34870577,Happy Home 3,158178970,Raquel,Staten Island,Randall Manor,40.63136,-74.12559,Shared room,13,1,9,2019-07-05,5.51,3,8
46049,35042058,"Big one bedroom apt, new and beautiful.",19342,Rivka,Manhattan,Upper West Side,40.79900,-73.96315,Entire home/apt,11,7,0,NaN,NaN,1,273
47160,35612982,Luggage drop off ONLY! Close to LGA & JFK,108512889,Syed,Queens,Sunnyside,40.73954,-73.92095,Shared room,12,1,0,NaN,NaN,1,359
47218,35642891,Beautiful room in Bushwick,268138154,Julio,Brooklyn,Bushwick,40.69640,-73.91898,Private room,10,1,2,2019-06-18,2.00,1,0
47979,36022650,Charming entire apartment in Hell's Kitchen,2967377,Aude,Manhattan,Hell's Kitchen,40.76279,-73.99463,Entire home/apt,15,2,0,NaN,NaN,1,139
48486,36280646,"Cable and wfi, L/G included.",272872092,Chris,Queens,Forest Hills,40.73657,-73.85088,Entire home/apt,16,9,1,2019-07-07,1.00,1,322

In [45]:
df[(df.price>max_threshold)]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
4377,2953058,Film Location,1177497,Jessica,Brooklyn,Clinton Hill,40.69137,-73.96723,Entire home/apt,8000,1,1,2016-09-15,0.03,11,365
6530,4737930,Spanish Harlem Apt,1235070,Olson,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,2015-01-02,0.02,1,0
9151,7003697,Furnished room in Astoria apartment,20582832,Kathrine,Queens,Astoria,40.76810,-73.91651,Private room,10000,100,2,2016-02-13,0.04,1,0
12342,9528920,"Quiet, Clean, Lit @ LES & Chinatown",3906464,Amy,Manhattan,Lower East Side,40.71355,-73.98507,Private room,9999,99,6,2016-01-01,0.14,1,83
17692,13894339,Luxury 1 bedroom apt. -stunning Manhattan views,5143901,Erin,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,2017-07-27,0.16,1,0
29238,22436899,1-BR Lincoln Center,72390391,Jelena,Manhattan,Upper West Side,40.77213,-73.98665,Entire home/apt,10000,30,0,NaN,NaN,1,83
29662,22779726,East 72nd Townhouse by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper East Side,40.76824,-73.95989,Entire home/apt,7703,1,0,NaN,NaN,12,146
30268,23377410,Beautiful/Spacious 1 bed luxury flat-TriBeCa/Soho,18128455,Rum,Manhattan,Tribeca,40.72197,-74.00633,Entire home/apt,8500,30,2,2018-09-18,0.18,1,251
40433,31340283,2br - The Heart of NYC: Manhattans Lower East ...,4382127,Matt,Manhattan,Lower East Side,40.71980,-73.98566,Entire home/apt,9999,30,0,NaN,NaN,1,365

In [55]:
lower_bound, upper_bound = df.price.quantile([0.01, 0.999])

lower_bound, upper_bound

(30.0, 3000.0)

In [56]:
final_df = df[(df.price>lower_bound) & (df.price<upper_bound)]

final_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [57]:
df.shape

(48895, 16)

In [58]:
final_df.shape

(48183, 16)

In [59]:
final_df.price.describe()

count    48183.000000
mean       148.772036
std        153.594795
min         31.000000
25%         70.000000
50%        110.000000
75%        179.000000
max       2999.000000
Name: price, dtype: float64